backend: 
  name: git-gateway
  branch: master

media_folder: "images/uploads"

collections: 
  - name: "friends" 
    label: "Friend"
    folder: "_friends"
    create: true
    slug: "{{name_slug}}"
    fields: 
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Name Slug", name: "name_slug", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}